### PR TITLE
Socket open timeout

### LINKED ISSUE #80: Remote connection attempts has no timeout
When connecting to a remote there is no specified timeout duration. If the connection for some reason is unavailable when trying to connect, the current retry loop will throw an error almost immediately as is fails to open a connection to the remote. It is probably better to handle this with a timeout using a retry loop.

### PR DESCRIPTION
**Pull request by msteinsto**
Closes #80. Adds a retry loop with a sleep duration between each attempt at opening the remote connection.  Timeout is set to 5 minutes

### CODE REVIEW

File: src/proxyfmu/client/proxy_slave.cpp [hunk 1]
```diff
@@ -62,7 +65,20 @@ proxy_slave::proxy_slave(const filesystem::path& fmuPath, const std::string& ins
...
+
+        int retries = 0;
+        while (retries < max_retries) {
+            std::cout << "[proxyfmu] Proxy slave: retry loop: retries: '" << retries << "'.." << std::endl;
+            try {
+                transport->open();
+                break;
+            } catch (const TTransportException& ex) {
+                if (retries++ > max_retries) {
+                    throw ex;
```
Comment (markaren) [inline src/proxyfmu/client/proxy_slave.cpp:77]: I think the correct way to rethrow should just be `throw`

**Comment by markaren** [comment]
Worth noting that this change is specifically for connections to the remote booter executable.
